package com.scarlatti.rxswing;

import com.scarlatti.rxswing.component.usr.MyCoolComponent;
import com.scarlatti.rxswing.component.ntv.RxJLabel;

import javax.swing.*;
import java.awt.*;

/**
 * ______    __                         __           ____             __     __  __  _
 * ___/ _ | / /__ ___ ___ ___ ____  ___/ /______    / __/______ _____/ /__ _/ /_/ /_(_)
 * __/ __ |/ / -_|_-<(_-</ _ `/ _ \/ _  / __/ _ \  _\ \/ __/ _ `/ __/ / _ `/ __/ __/ /
 * /_/ |_/_/\__/___/___/\_,_/_//_/\_,_/_/  \___/ /___/\__/\_,_/_/ /_/\_,_/\__/\__/_/
 * Saturday, 8/25/2018
 */
public class TestCmp {
    private JPanel panel;
    private JButton upButton;
    private JButton downButton;
    private MyCoolComponent coolComponent;

    public TestCmp() {
        coolComponent = new MyCoolComponent();
        RxJLabel label1 = coolComponent.render();
        panel.add(label1);
        RdrMger.getInstance().mountComponent(coolComponent.getNtvRndId(), label1);
        upButton.addActionListener(e -> coolComponent.setState(coolComponent.getState() + 1));
        downButton.addActionListener(e -> coolComponent.setState(coolComponent.getState() - 1));
    }

    public JPanel getPanel() {
        return panel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        upButton = new JButton();
        upButton.setText("Up");
        panel.add(upButton);
        downButton = new JButton();
        downButton.setText("Down");
        panel.add(downButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }
}
