package com.scarlatti.rxswing;

import com.scarlatti.rxswing.component.ntv.RxJLabel;
import com.scarlatti.rxswing.component.ntv.RxJPanel;
import com.scarlatti.rxswing.component.usr.LottoComponent;
import com.scarlatti.rxswing.component.usr.MyCoolComponent;
import com.scarlatti.rxswing.inspect.RxNode;

import javax.swing.*;
import java.awt.*;

/**
 * ______    __                         __           ____             __     __  __  _
 * ___/ _ | / /__ ___ ___ ___ ____  ___/ /______    / __/______ _____/ /__ _/ /_/ /_(_)
 * __/ __ |/ / -_|_-<(_-</ _ `/ _ \/ _  / __/ _ \  _\ \/ __/ _ `/ __/ / _ `/ __/ __/ /
 * /_/ |_/_/\__/___/___/\_,_/_//_/\_,_/_/  \___/ /___/\__/\_,_/_/ /_/\_,_/\__/\__/_/
 * Saturday, 8/25/2018
 */
public class TestCmp4 {
    private JPanel jPanel;
    private JButton upButton;
    private JButton downButton;

    public TestCmp4() {
//        LottoComponent lottoComponent = new LottoComponent();
//        JLabel label1 = new JLabel("what1");
//        JLabel label2 = new JLabel("what2");
//
//        jPanel.add(label1);
//        jPanel.add(label2);
//
//        RdrMger.getInstance().getSwComponentStore().putIfAbsent("lottoComponent/com.scarlatti.rxswing.component.ntv.RxJPanel[0]", jPanel);
//        RdrMger.getInstance().getSwComponentStore().putIfAbsent("lottoComponent/com.scarlatti.rxswing.component.ntv.RxJPanel[0]/com.scarlatti.rxswing.component.ntv.RxJLabel[0]", label1);
//        RdrMger.getInstance().getSwComponentStore().putIfAbsent("lottoComponent/com.scarlatti.rxswing.component.ntv.RxJPanel[0]/com.scarlatti.rxswing.component.ntv.RxJLabel[1]", label2);
//
//        lottoComponent.getLifecycleManager().addToStore(RdrMger.getInstance().getRxComponentStore(), "lottoComponent");
//
//        RdrMger.getInstance().getCurrentDom().setRoot(
//            Rx.node(RxJPanel.class)
//                .id("lottoComponent/com.scarlatti.rxswing.component.ntv.RxJPanel[0]")
//                .child(
//                    Rx.node(RxJLabel.class)
//                        .id("lottoComponent/com.scarlatti.rxswing.component.ntv.RxJPanel[0]/com.scarlatti.rxswing.component.ntv.RxJLabel[0]")
//                        .props("text", "what")
//                )
//                .child(
//                    Rx.node(RxJLabel.class)
//                        .id("lottoComponent/com.scarlatti.rxswing.component.ntv.RxJPanel[0]/com.scarlatti.rxswing.component.ntv.RxJLabel[1]")
//                        .props("text", "what")
//                )
//        );

        // so theoretically, all this preparation should be able to removed and replaced with
        // a single call to Rx.render()

        Rx.render(() -> Rx.node(LottoComponent.class), jPanel);

        RxNode domRoot = RdrMger.getInstance().getCurrentDom().getRoot();
        LottoComponent lottoComponent = (LottoComponent) RdrMger.getInstance().getRxComponentStore().get(domRoot.getId());

        upButton.addActionListener(e -> {
            lottoComponent.setStateTemp(lottoComponent.getState() + 1);
        });

        downButton.addActionListener(e -> {
            lottoComponent.setStateTemp(lottoComponent.getState() - 1);
        });
    }

    public JPanel getjPanel() {
        return jPanel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        jPanel = new JPanel();
        jPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        upButton = new JButton();
        upButton.setText("Up");
        jPanel.add(upButton);
        downButton = new JButton();
        downButton.setText("Down");
        jPanel.add(downButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return jPanel;
    }
}
