package com.scarlatti.rxswing;

import com.scarlatti.rxswing.component.RxJLabel;

import javax.swing.*;
import java.awt.*;

/**
 * ______    __                         __           ____             __     __  __  _
 * ___/ _ | / /__ ___ ___ ___ ____  ___/ /______    / __/______ _____/ /__ _/ /_/ /_(_)
 * __/ __ |/ / -_|_-<(_-</ _ `/ _ \/ _  / __/ _ \  _\ \/ __/ _ `/ __/ / _ `/ __/ __/ /
 * /_/ |_/_/\__/___/___/\_,_/_//_/\_,_/_/  \___/ /___/\__/\_,_/_/ /_/\_,_/\__/\__/_/
 * Saturday, 8/25/2018
 */
public class TestCmp {
    private JPanel panel;
    private JButton upButton;
    private JButton downButton;
    private RxJLabel label;
    private int count = 0; // this is the single object in the state.

    public TestCmp() {
        addLabel();
        upButton.addActionListener(e -> setState(count + 1));
        downButton.addActionListener(e -> setState(count - 1));
    }

    // count is the single object in the state.
    public void setState(int count) {
        this.count = count;

        // now initiate render.
        RdrMgr.getInstance().pleaseRdr(this, label);
    }

    public RxJLabel render() {
        return new RxJLabel(String.valueOf(count));
    }

    public JPanel getPanel() {
        return panel;
    }

    // this is the tmp one-time creation...
    private void addLabel() {
        label = new RxJLabel("0");
        panel.add(label);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        upButton = new JButton();
        upButton.setText("Up");
        panel.add(upButton);
        downButton = new JButton();
        downButton.setText("Down");
        panel.add(downButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }
}
